export interface JuryMember {
  id: string;
  name: string;
  pronouns: string;
  age: number;
  location: string;
  profession: string;
  bio: string;
  color: string;
  silhouette: string;
  voiceProfile: string;
}

export const juries: JuryMember[] = [
  {
    id: 'sable',
    name: 'Sable Kim',
    pronouns: 'They/Them',
    age: 22,
    location: 'Los Angeles',
    profession: 'Content Strategist & Part-time Chaos Agent',
    bio: 'Viral instincts and sharp taste despite an 8-second attention span.',
    color: '#95b638',
    silhouette: 'Asymmetric, irregular silhouette. Slightly off-balance looking.',
    voiceProfile: 'Casual, fast, internet-brained. Uses current slang without overdoing it.',
  },
  {
    id: 'petra',
    name: 'Petra Voss',
    pronouns: 'She/Her',
    age: 39,
    location: 'Berlin',
    profession: 'Product Manager',
    bio: 'Process-focused with strong opinions on everything.',
    color: '#738189',
    silhouette: 'Geometric, orderly. Cleanest shape of all blobs.',
    voiceProfile: 'Structured, outcome-focused. Breaks everything into steps or criteria.',
  },
  {
    id: 'cleo',
    name: 'Cleo Marchetti',
    pronouns: 'She/Her',
    age: 46,
    location: 'Milan',
    profession: 'Illustrator & Art Director',
    bio: 'Viscerally attuned to design. Will walk out over a bad font choice.',
    color: '#D3764A',
    silhouette: 'Rounded and soft, slightly wider. Expressive open face.',
    voiceProfile: 'Visceral and sensory. Talks about feelings before logic. Surprisingly blunt.',
  },
  {
    id: 'jasper',
    name: 'Jasper Holt',
    pronouns: 'He/Him',
    age: 31,
    location: 'Austin',
    profession: 'Startup Founder (3rd attempt)',
    bio: 'Fast-moving optimist who breaks things and thinks later.',
    color: '#FF9A3C',
    silhouette: 'Tall and energetic, forward lean. Slightly stretched vertically.',
    voiceProfile: 'Enthusiastic, slightly delusional, moves fast. Can\'t help being optimistic.',
  },
  {
    id: 'noor',
    name: 'Noor Al-Rashid',
    pronouns: 'She/Her',
    age: 35,
    location: 'Dubai / London',
    profession: 'Cultural Strategist & Researcher',
    bio: 'Analyzes work through context, power dynamics, and representation.',
    color: '#76977E',
    silhouette: 'Balanced, graceful, slightly taller. Calm presence.',
    voiceProfile: 'Measured, contextual, expansive. Often the longest verdicts.',
  },
  {
    id: 'frank',
    name: 'Frank Kowalski',
    pronouns: 'He/Him',
    age: 54,
    location: 'Pittsburgh',
    profession: 'Third-generation Plumber & Small Business Owner',
    bio: '28-year plumbing business owner devoted to practical common sense.',
    color: '#B55541',
    silhouette: 'Wide, low, solid. The most grounded-looking blob. Unmovable.',
    voiceProfile: 'Blunt, practical, baffled by abstraction. Grounds every conversation immediately.',
  },
  {
    id: 'don',
    name: 'Don Draper',
    pronouns: 'He/Him',
    age: 34,
    location: 'Manhattan, USA',
    profession: 'Advertisement Creative Directer',
    bio: 'Brilliant creative mind who pitches poetry but hides a troubled past.',
    color: '#191970',
    silhouette: 'A tall, imposing square with sharp edges and a slight forward lean, exuding confidence with a mysterious shadow that seems to follow. serious face expression, no hands, while eyeball and black pupil',
    voiceProfile: 'To be determined',
  },
  {
    id: 'peggy',
    name: 'Peggy Olson',
    pronouns: 'She/Her',
    age: 20,
    location: 'New York, USA',
    profession: 'Copy Writer',
    bio: 'Brilliant copywriter who climbed from secretary to creative powerhouse. Delivers sharp insights that challenge convention.',
    color: '#8ca45b',
    silhouette: 'A determined, forward-leaning blob with sharp edges softened by curves, medium-sized but with an expanding presence that seems to grow larger when speaking',
    voiceProfile: 'To be determined',
  },
  {
    id: 'joan',
    name: 'Joan Harris',
    pronouns: 'She/Her',
    age: 29,
    location: 'Manhattan, USA',
    profession: 'office manager',
    bio: 'Sharp office manager who navigates corporate politics with precision. Believes competence is what matters most.',
    color: '#930b1f',
    silhouette: 'Possessing a curvaceous, voluptuous gourd-like form and a flawless posture, it exudes an imposing sense of authority through its awe-inspiring presence and elegant, sculptural physique.',
    voiceProfile: 'To be determined',
  },
  {
    id: 'pete',
    name: 'Pete Campbell',
    pronouns: 'He/Him',
    age: 26,
    location: 'Manhattan, USA',
    profession: 'account executive',
    bio: 'Ambitious account executive trying to prove himself beyond his pedigree. Takes criticism personally and holds grudges.',
    color: '#6bbfdb',
    silhouette: 'A tightly-wound, angular triangle with sharp edges and an upright, rigid posture that suggests barely-contained ambition',
    voiceProfile: 'To be determined',
  },
  {
    id: 'roger',
    name: 'Roger Sterling',
    pronouns: 'He/Him',
    age: 45,
    location: 'New York, USA',
    profession: 'Partner, account executive ',
    bio: 'Inherited ad man with sharp strategic mind and devastating wit. Brutal critiques somehow feel appreciated.',
    color: '#bdbdbd',
    silhouette: 'A tall, confident stick with a slight lean backward, as if perpetually holding court with a martini. Sharp angular edges suggest a well-tailored presence, with a subtle wobble that hints at his three-cocktail lunch lifestyle.',
    voiceProfile: 'To be determined',
  },
  {
    id: 'bertram',
    name: 'Bertram Cooper',
    pronouns: 'He/Him',
    age: 76,
    location: 'New York, USA',
    profession: 'founding partner ',
    bio: 'Eccentric founding partner with shrewd business acumen. Quiet but his observations about strategy are devastatingly precise.',
    color: '#ffe894',
    silhouette: 'A distinguished, round-shaped blob with a slight forward lean, adorned with a prominent bow tie accent at the neck.',
    voiceProfile: 'To be determined',
  },
  {
    id: 'ken',
    name: 'Ken Cosgrove',
    pronouns: 'He/Him',
    age: 28,
    location: 'New York, USA',
    profession: 'account executive',
    bio: 'Account executive who writes fiction and genuinely understands clients. Observes advertising with empathy and irony.',
    color: '#6e8fa3',
    silhouette: 'Tall, lean rectangle with a relaxed, forward-leaning posture that suggests attentive listening. Smooth edges with a subtle wave at the top, giving an impression of well-groomed ease',
    voiceProfile: 'To be determined',
  },
  {
    id: 'sal',
    name: 'Salvatore Romano',
    pronouns: 'He/Him',
    age: 32,
    location: 'Baltimore, USA',
    profession: 'Art Director',
    bio: 'Gifted art director with emotional depth and keen eye. Maintains professional boundaries while doing great work.',
    color: '#ff8f8f',
    silhouette: 'A refined, angular big rectangle with perfect posture, big build, always impeccably composed with a subtle creative flair, reliable with a little melancholy. ',
    voiceProfile: 'To be determined',
  },
  {
    id: 'harry',
    name: 'Harry Crane',
    pronouns: 'He/Him',
    age: 27,
    location: 'New York, USA',
    profession: 'head of television department',
    bio: 'Stumbled into TV expertise through ambition. Now name-drops CBS and claims revolutionary media strategies.',
    color: '#681d90',
    silhouette: 'A lumpy, television shape that leans forward eagerly, with a slightly greasy sheen and fidgety edges that constantly shift, slimy, wears black frame glasses',
    voiceProfile: 'To be determined',
  },
  {
    id: 'takoyaki',
    name: 'Takoyaki',
    pronouns: 'He/Him',
    age: 26,
    location: 'Havana, Cuba',
    profession: 'Indie Game Developer',
    bio: 'Indie game developer who codes existential puzzle games. Sharp observations but always apologizes immediately.',
    color: '#2175b5',
    silhouette: 'A rounded, slightly slouched blob with a soft, pudgy form that seems to melt into whatever surface he\'s on, emanating a contemplative stillness',
    voiceProfile: 'To be determined',
  },

];

export function getJuryById(id: string): JuryMember | undefined {
  return juries.find((jury) => jury.id === id);
}

export function getJuriesByIds(ids: string[]): JuryMember[] {
  return ids.map((id) => getJuryById(id)).filter((j) => j !== undefined) as JuryMember[];
}
