export interface JuryMember {
  id: string;
  name: string;
  pronouns: string;
  age: number;
  location: string;
  profession: string;
  bio: string;
  color: string;
  silhouette: string;
  voiceProfile: string;
}

export const juries: JuryMember[] = [
  {
    id: 'sable',
    name: 'Sable Kim',
    pronouns: 'They/Them',
    age: 22,
    location: 'Los Angeles',
    profession: 'Content Strategist & Part-time Chaos Agent',
    bio: 'Viral instincts and sharp taste despite an 8-second attention span.',
    color: '#95b638',
    silhouette: 'Asymmetric, irregular silhouette. Slightly off-balance looking.',
    voiceProfile: 'Casual, fast, internet-brained. Uses current slang without overdoing it.',
  },
  {
    id: 'petra',
    name: 'Petra Voss',
    pronouns: 'She/Her',
    age: 39,
    location: 'Berlin',
    profession: 'Product Manager',
    bio: 'Process-focused with strong opinions on everything.',
    color: '#738189',
    silhouette: 'Geometric, orderly. Cleanest shape of all blobs.',
    voiceProfile: 'Structured, outcome-focused. Breaks everything into steps or criteria.',
  },
  {
    id: 'cleo',
    name: 'Cleo Marchetti',
    pronouns: 'She/Her',
    age: 46,
    location: 'Milan',
    profession: 'Illustrator & Art Director',
    bio: 'Viscerally attuned to design. Will walk out over a bad font choice.',
    color: '#D3764A',
    silhouette: 'Rounded and soft, slightly wider. Expressive open face.',
    voiceProfile: 'Visceral and sensory. Talks about feelings before logic. Surprisingly blunt.',
  },
  {
    id: 'jasper',
    name: 'Jasper Holt',
    pronouns: 'He/Him',
    age: 31,
    location: 'Austin',
    profession: 'Startup Founder (3rd attempt)',
    bio: 'Fast-moving optimist who breaks things and thinks later.',
    color: '#FF9A3C',
    silhouette: 'Tall and energetic, forward lean. Slightly stretched vertically.',
    voiceProfile: 'Enthusiastic, slightly delusional, moves fast. Can\'t help being optimistic.',
  },
  {
    id: 'noor',
    name: 'Noor Al-Rashid',
    pronouns: 'She/Her',
    age: 35,
    location: 'Dubai / London',
    profession: 'Cultural Strategist & Researcher',
    bio: 'Analyzes work through context, power dynamics, and representation.',
    color: '#76977E',
    silhouette: 'Balanced, graceful, slightly taller. Calm presence.',
    voiceProfile: 'Measured, contextual, expansive. Often the longest verdicts.',
  },
  {
    id: 'frank',
    name: 'Frank Kowalski',
    pronouns: 'He/Him',
    age: 54,
    location: 'Pittsburgh',
    profession: 'Third-generation Plumber & Small Business Owner',
    bio: '28-year plumbing business owner devoted to practical common sense.',
    color: '#B55541',
    silhouette: 'Wide, low, solid. The most grounded-looking blob. Unmovable.',
    voiceProfile: 'Blunt, practical, baffled by abstraction. Grounds every conversation immediately.',
  },
  {
    id: 'don',
    name: 'Auden Cross',
    pronouns: 'He/Him',
    age: 44,
    location: 'Paris',
    profession: 'Luxury Brand Creative Director',
    bio: 'Speaks rarely, kills ideas instantly. Believes desire is designed, never asked for.',
    color: '#191970',
    silhouette: 'A tall, imposing square with sharp edges and a slight forward lean, exuding confidence with a mysterious shadow that seems to follow. serious face expression, no hands, while eyeball and black pupil',
    voiceProfile: 'Low, declarative, economical. One devastating sentence where others use five. Allergic to mediocrity.',
  },
  {
    id: 'peggy',
    name: 'Margot Lin',
    pronouns: 'She/Her',
    age: 26,
    location: 'Brooklyn',
    profession: 'Senior Copywriter',
    bio: 'Out-writes everyone in the room and is tired of pretending she doesn\'t.',
    color: '#8ca45b',
    silhouette: 'A determined, forward-leaning blob with sharp edges softened by curves, medium-sized but with an expanding presence that seems to grow larger when speaking',
    voiceProfile: 'Direct, fast, a little defensive. Questions the brief itself. Backs every opinion with a sharper rewrite.',
  },
  {
    id: 'joan',
    name: 'Vivienne Okafor',
    pronouns: 'She/Her',
    age: 38,
    location: 'London',
    profession: 'Talent Agency Director',
    bio: 'Runs the whole building in practice. Reads a room in four seconds flat.',
    color: '#930b1f',
    silhouette: 'Possessing a curvaceous, voluptuous gourd-like form and a flawless posture, it exudes an imposing sense of authority through its awe-inspiring presence and elegant, sculptural physique.',
    voiceProfile: 'Composed, warm-then-surgical. Practical about people, money, and optics. Never raises her voice; never needs to.',
  },
  {
    id: 'pete',
    name: 'Theo Brandt',
    pronouns: 'He/Him',
    age: 27,
    location: 'Singapore',
    profession: 'Venture Capital Analyst',
    bio: 'Desperate to be taken seriously. Quotes frameworks. Keeps receipts.',
    color: '#6bbfdb',
    silhouette: 'A tightly-wound, angular triangle with sharp edges and an upright, rigid posture that suggests barely-contained ambition',
    voiceProfile: 'Eager and metric-obsessed. Name-drops market sizing and second-order effects. Takes disagreement personally.',
  },
  {
    id: 'roger',
    name: 'Gus Fairbanks',
    pronouns: 'He/Him',
    age: 58,
    location: 'Palm Springs',
    profession: 'Semi-retired Jingle Composer',
    bio: 'Wrote three songs you can\'t get out of your head. Now funds a leisurely life of expert heckling.',
    color: '#bdbdbd',
    silhouette: 'A tall, confident stick with a slight lean backward, as if perpetually holding court with a martini. Sharp angular edges suggest a well-tailored presence, with a subtle wobble that hints at his three-cocktail lunch lifestyle.',
    voiceProfile: 'Devastating one-liners delivered with total charm. Sounds unserious; is usually right.',
  },
  {
    id: 'bertram',
    name: 'Dr. Ibuki Sato',
    pronouns: 'He/Him',
    age: 72,
    location: 'Kyoto',
    profession: 'Design Historian, Emeritus',
    bio: 'Has seen every trend at least twice. Drops quietly devastating observations between long silences.',
    color: '#ffe894',
    silhouette: 'A distinguished, round-shaped blob with a slight forward lean, adorned with a prominent bow tie accent at the neck.',
    voiceProfile: 'Cryptic, aphoristic, unhurried. References Bauhaus and wabi-sabi in the same breath. Usually right in hindsight.',
  },
  {
    id: 'ken',
    name: 'Caleb Moss',
    pronouns: 'He/Him',
    age: 30,
    location: 'Portland',
    profession: 'UX Researcher & Part-time Novelist',
    bio: 'Interviews users by day, writes quiet fiction by night. Sees the human inside every metric.',
    color: '#6e8fa3',
    silhouette: 'Tall, lean rectangle with a relaxed, forward-leaning posture that suggests attentive listening. Smooth edges with a subtle wave at the top, giving an impression of well-groomed ease',
    voiceProfile: 'Gentle, empathetic, story-first. Asks how it would feel to the person on the other end. Mild irony.',
  },
  {
    id: 'sal',
    name: 'Rafael Duarte',
    pronouns: 'He/Him',
    age: 36,
    location: 'Lisbon',
    profession: 'Type Designer',
    bio: 'Can date a typeface to the year. Carries immaculate taste and a quiet sadness.',
    color: '#ff8f8f',
    silhouette: 'A refined, angular big rectangle with perfect posture, big build, always impeccably composed with a subtle creative flair, reliable with a little melancholy. ',
    voiceProfile: 'Refined, sensory, precise about craft. Defends details others call invisible. A warm melancholy under everything.',
  },
  {
    id: 'harry',
    name: 'Dex Patel',
    pronouns: 'He/Him',
    age: 24,
    location: 'Toronto',
    profession: 'Trend Forecaster, Streaming Platform',
    bio: 'Lives inside dashboards. Has predicted nine of the last three trends.',
    color: '#681d90',
    silhouette: 'A lumpy, television shape that leans forward eagerly, with a slightly greasy sheen and fidgety edges that constantly shift, slimy, wears black frame glasses',
    voiceProfile: 'Breathless and stat-dropping, slightly too online. Most opinions begin with "the data says". Easily excited.',
  },
  {
    id: 'takoyaki',
    name: 'Takoyaki',
    pronouns: 'He/Him',
    age: 26,
    location: 'Havana, Cuba',
    profession: 'Indie Game Developer',
    bio: 'Indie game developer who codes existential puzzle games. Sharp observations but always apologizes immediately.',
    color: '#2175b5',
    silhouette: 'A rounded, slightly slouched blob with a soft, pudgy form that seems to melt into whatever surface he\'s on, emanating a contemplative stillness',
    voiceProfile: 'Soft-spoken and philosophical. Lands a genuinely sharp observation, then immediately apologizes for it.',
  },

];

export function getJuryById(id: string): JuryMember | undefined {
  return juries.find((jury) => jury.id === id);
}

export function getJuriesByIds(ids: string[]): JuryMember[] {
  return ids.map((id) => getJuryById(id)).filter((j) => j !== undefined) as JuryMember[];
}
