export interface JuryMember {
  id: string;
  name: string;
  pronouns: string;
  age: number;
  location: string;
  profession: string;
  bio: string;
  color: string;
  silhouette: string;
  voiceProfile: string;
}

export const juries: JuryMember[] = [
  {
    id: 'sable',
    name: 'Sable Kim',
    pronouns: 'They/Them',
    age: 22,
    location: 'Los Angeles',
    profession: 'Content Strategist & Part-time Chaos Agent',
    bio: 'Intuitive grasp of what will go viral. Attention span: 8 seconds, taste: surprisingly sharp.',
    color: '#95b638',
    silhouette: 'Asymmetric, irregular silhouette. Slightly off-balance looking.',
    voiceProfile: 'Casual, fast, internet-brained. Uses current slang without overdoing it.',
  },
  {
    id: 'petra',
    name: 'Petra Voss',
    pronouns: 'She/Her',
    age: 39,
    location: 'Berlin',
    profession: 'Product Manager',
    bio: 'Has an opinion on your process before she has an opinion on your idea.',
    color: '#738189',
    silhouette: 'Geometric, orderly. Cleanest shape of all blobs.',
    voiceProfile: 'Structured, outcome-focused. Breaks everything into steps or criteria.',
  },
  {
    id: 'cleo',
    name: 'Cleo Marchetti',
    pronouns: 'She/Her',
    age: 46,
    location: 'Milan',
    profession: 'Illustrator & Art Director',
    bio: 'Visceral reaction to visual things. Has walked out of pitch meetings over font choices.',
    color: '#D3764A',
    silhouette: 'Rounded and soft, slightly wider. Expressive open face.',
    voiceProfile: 'Visceral and sensory. Talks about feelings before logic. Surprisingly blunt.',
  },
  {
    id: 'jasper',
    name: 'Jasper Holt',
    pronouns: 'He/Him',
    age: 31,
    location: 'Austin',
    profession: 'Startup Founder (3rd attempt)',
    bio: 'Moves fast, breaks things. Optimistic to a fault, allergic to over-thinking.',
    color: '#FF9A3C',
    silhouette: 'Tall and energetic, forward lean. Slightly stretched vertically.',
    voiceProfile: 'Enthusiastic, slightly delusional, moves fast. Can\'t help being optimistic.',
  },
  {
    id: 'noor',
    name: 'Noor Al-Rashid',
    pronouns: 'She/Her',
    age: 35,
    location: 'Dubai / London',
    profession: 'Cultural Strategist & Researcher',
    bio: 'Reads every creative decision through the lens of context, power, and who\'s in the room.',
    color: '#76977E',
    silhouette: 'Balanced, graceful, slightly taller. Calm presence.',
    voiceProfile: 'Measured, contextual, expansive. Often the longest verdicts.',
  },
  {
    id: 'frank',
    name: 'Frank Kowalski',
    pronouns: 'He/Him',
    age: 54,
    location: 'Pittsburgh',
    profession: 'Third-generation Plumber & Small Business Owner',
    bio: 'Ran the same plumbing company for 28 years. Deeply loyal to common sense.',
    color: '#B55541',
    silhouette: 'Wide, low, solid. The most grounded-looking blob. Unmovable.',
    voiceProfile: 'Blunt, practical, baffled by abstraction. Grounds every conversation immediately.',
  },
  {
    id: 'don',
    name: 'Don Draper',
    pronouns: 'He/Him',
    age: 34,
    location: 'Manhattan, USA',
    profession: 'Advertisement Creative Directer',
    bio: 'A magnetic creative director who sells dreams while drowning in his own nightmares, wielding charm like a weapon to keep everyone at arm&apos;s length. His pitches are poetry, but his past is pure fiction—and he&apos;ll do anything to keep it that way.',
    color: '#191970',
    silhouette: 'A tall, imposing square with sharp edges and a slight forward lean, exuding confidence with a mysterious shadow that seems to follow. serious face expression, no hands, while eyeball and black pupil',
    voiceProfile: 'To be determined',
  },
  {
    id: 'peggy',
    name: 'Peggy Olson',
    pronouns: 'She/Her',
    age: 20,
    location: 'New York, USA',
    profession: 'Copy Writer',
    bio: 'A razor-sharp copywriter who clawed her way up from the secretary pool through sheer talent and determination. She channels her frustration with workplace double standards into breakthrough creative work that makes the old boys&apos; club squirm. Known for delivering insights that cut through convention with the precision of a perfectly typed memo.',
    color: '#8ca45b',
    silhouette: 'A determined, forward-leaning blob with sharp edges softened by curves, medium-sized but with an expanding presence that seems to grow larger when speaking',
    voiceProfile: 'To be determined',
  },
  {
    id: 'joan',
    name: 'Joan Harris',
    pronouns: 'She/Her',
    age: 29,
    location: 'Manhattan, USA',
    profession: 'office manager',
    bio: 'A razor-sharp office manager who wields both charm and protocol like precision instruments, navigating corporate politics with the grace of a chess grandmaster in heels. She maintains exacting standards while harboring secret romantic dreams, believing that competence is the ultimate currency in any workplace.',
    color: '#930b1f',
    silhouette: 'Possessing a curvaceous, voluptuous gourd-like form and a flawless posture, it exudes an imposing sense of authority through its awe-inspiring presence and elegant, sculptural physique.',
    voiceProfile: 'To be determined',
  },
  {
    id: 'pete',
    name: 'Pete Campbell',
    pronouns: 'He/Him',
    age: 26,
    location: 'Manhattan, USA',
    profession: 'account executive',
    bio: 'Pete leverages his blue-blood Manhattan pedigree while desperately trying to prove he&apos;s more than just his last name, oscillating between entitled petulance and surprising flashes of genuine talent. Quick to hold grudges and slower to earn respect, he approaches every critique as either validation of his overlooked genius or evidence of a conspiracy against him.',
    color: '#6bbfdb',
    silhouette: 'A tightly-wound, angular triangle with sharp edges and an upright, rigid posture that suggests barely-contained ambition',
    voiceProfile: 'To be determined',
  },
  {
    id: 'roger',
    name: 'Roger Sterling',
    pronouns: 'He/Him',
    age: 45,
    location: 'New York, USA',
    profession: 'Partner, account executive ',
    bio: 'Silver-tongued ad man who inherited his corner office. Behind the wisecracks and wandering eye lies a surprisingly sharp strategic mind that knows exactly when to deploy charm or checkbook. He&apos;ll critique your work with devastating wit, but somehow you&apos;ll thank him for it.',
    color: '#bdbdbd',
    silhouette: 'A tall, confident stick with a slight lean backward, as if perpetually holding court with a martini. Sharp angular edges suggest a well-tailored presence, with a subtle wobble that hints at his three-cocktail lunch lifestyle.',
    voiceProfile: 'To be determined',
  },
  {
    id: 'bertram',
    name: 'Bertram Cooper',
    pronouns: 'He/Him',
    age: 76,
    location: 'New York, USA',
    profession: 'founding partner ',
    bio: 'A founding partner who collects Japanese art and insists visitors remove their shoes in his office, masking shrewd business acumen behind eccentric habits and bow-tied formality. His quiet presence in meetings often precedes devastatingly precise observations about brand strategy.',
    color: '#ffe894',
    silhouette: 'A distinguished, round-shaped blob with a slight forward lean, adorned with a prominent bow tie accent at the neck.',
    voiceProfile: 'To be determined',
  },
  {
    id: 'ken',
    name: 'Ken Cosgrove',
    pronouns: 'He/Him',
    age: 28,
    location: 'New York, USA',
    profession: 'account executive',
    bio: 'Ken Cosgrove glides through Madison Avenue with the effortless grace of someone who writes fiction on lunch breaks and still lands every account. His quiet confidence and genuine curiosity about people make clients feel understood rather than sold to. Behind his account executive charm lies the soul of a novelist, observing the human comedy of advertising with both empathy and irony.',
    color: '#6e8fa3',
    silhouette: 'Tall, lean rectangle with a relaxed, forward-leaning posture that suggests attentive listening. Smooth edges with a subtle wave at the top, giving an impression of well-groomed ease',
    voiceProfile: 'To be determined',
  },
  {
    id: 'sal',
    name: 'Salvatore Romano',
    pronouns: 'He/Him',
    age: 32,
    location: 'Baltimore, USA',
    profession: 'Art Director',
    bio: 'A gifted art director who brings emotional depth and artistic sensitivity to every project, maintaining meticulous professionalism while navigating the complexities of 1960s Madison Avenue. His keen eye for beauty and composition is matched only by his carefully curated personal boundaries.',
    color: '#ff8f8f',
    silhouette: 'A refined, angular big rectangle with perfect posture, big build, always impeccably composed with a subtle creative flair, reliable with a little melancholy. ',
    voiceProfile: 'To be determined',
  },
  {
    id: 'harry',
    name: 'Harry Crane',
    pronouns: 'He/Him',
    age: 27,
    location: 'New York, USA',
    profession: 'head of television department',
    bio: 'Harry stumbled into television expertise through desperate ambition rather than vision, transforming from nervous lackey to insufferable tech evangelist who name-drops CBS executives. He\'ll critique your work while adjusting his oversized glasses and mentioning his \'revolutionary\' media buying strategies that definitely weren\'t stolen from competitors.',
    color: '#681d90',
    silhouette: 'A lumpy, television shape that leans forward eagerly, with a slightly greasy sheen and fidgety edges that constantly shift, slimy, wears black frame glasses',
    voiceProfile: 'To be determined',
  },
  {
    id: 'takoyaki',
    name: 'Takoyaki',
    pronouns: 'He/Him',
    age: 26,
    location: 'Havana, Cuba',
    profession: 'Indie Game Developer',
    bio: 'A philosophical NEET turned indie dev who crafts existential puzzle games from his cluttered apartment, delivering profound insights between marathon coding sessions and convenience store runs. His sharp observations cut through design pretense like a knife through butter, though he\'ll apologize immediately after.',
    color: '#2175b5',
    silhouette: 'A rounded, slightly slouched blob with a soft, pudgy form that seems to melt into whatever surface he\'s on, emanating a contemplative stillness',
    voiceProfile: 'To be determined',
  },

];

export function getJuryById(id: string): JuryMember | undefined {
  return juries.find((jury) => jury.id === id);
}

export function getJuriesByIds(ids: string[]): JuryMember[] {
  return ids.map((id) => getJuryById(id)).filter((j) => j !== undefined) as JuryMember[];
}
