// Single source of truth for juror image paths.
// Thumbs are small WebP renders generated by scripts/generate-images.mjs;
// the full-size PNGs remain for the iOS Safari sprite fallback in the 3D stage.
export const juryThumb = (id: string) => `/jury/thumbs/${id}.webp`;
export const jurySprite = (id: string) => `/jury/${id}.png`;
